### ISSUE TITLE
Publishing a modpack

### ISSUE THREAD

**Issue by Xikaro** [juraj-hrivnak/Pakku#60] opened 2024-11-02 22:00 UTC
I would like to be able to automatically publish the modpack to curseforge and modrinth :D

implement a deploy command that does the export and then sends the files to CurseForge or Modrinth.

**Comment by juraj-hrivnak** [comment] 2024-11-02 23:04
Duplicate of #53

**Closed** 2024-11-02 23:05 UTC
